# Generated by Django 3.2.16 on 2022-12-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0005_alter_planet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
