# Generated by Django 3.2.16 on 2022-12-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0006_planet_updated_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planet',
            options={'ordering': ['-updated_on']},
        ),
    ]
